Repository andrewk10/AutoCompliance, pull requests merged in 2022-03, with the labels that each got.

#12 Wiki and Documentation Establishment
  .github/workflows/codeql-analysis-feature.yml
  .github/workflows/python-app-feature.yml
  .gitignore
  .idea/AutoCompliance.iml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  docs/_config.yml
  docs/guidelines/design/index.md
  docs/guidelines/index.md
  docs/index.md
  docs/research/index.md
  docs/research/proposal/assets/Figure1_1Edited.png
  docs/research/proposal/bibliography/index.md
  docs/research/proposal/index.md
  docs/wiki/index.md
  docs/wiki/usage/index.md
Labels: documentation, enhancement, help wanted, good first issue

#19 develop to main for documentation purposes
  .github/workflows/codeql-analysis-feature.yml
  .github/workflows/codeql-analysis-sprint.yml
  .github/workflows/python-app-feature.yml
  .github/workflows/python-app-sprint.yml
  .gitignore
  .idea/AutoCompliance.iml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  docs/_config.yml
  docs/guidelines/design/index.md
  docs/guidelines/index.md
  docs/index.md
  docs/research/index.md
  docs/research/proposal/assets/Figure1_1Edited.png
  docs/research/proposal/bibliography/index.md
  docs/research/proposal/index.md
  docs/wiki/index.md
  docs/wiki/usage/index.md
Labels: documentation

#21 [FIX] for help menue and added requirements.txt
  .gitignore
  requirements.txt
  src/main.py
  src/net_propagation.py
Labels: documentation, enhancement, help wanted, good first issue

#20 Adding all strings (where possible) to the strings.py script.
  .github/workflows/codeql-analysis-feature.yml
  .github/workflows/python-app-feature.yml
  dev_setup.sh
  src/main.py
  src/net_propagation.py
  src/strings.py
  src/test_net_propagation.py
Labels: documentation, enhancement, help wanted, good first issue

#25 Tests for Net Propagation Functions
  .circleci/config.yml
  .github/workflows/codeql-analysis-feature.yml
  .github/workflows/python-app-feature.yml
  dev_setup.sh
  docs/wiki/usage/index.md
  requirements.txt
  run_tests.sh
  src/__pycache__/net_propagation.cpython-310-pytest-6.2.5.pyc
  src/__pycache__/net_propagation.cpython-310.pyc
  src/__pycache__/strings.cpython-310.pyc
  src/__pycache__/test_net_propagation.cpython-310-pytest-6.2.5.pyc
  src/main.py
  src/net_propagation.py
  src/strings.py
  src/test_files/file.txt
  src/test_files/ip_list.txt
  src/test_files/passwords_list.txt
  src/test_net_propagation.py
Labels: documentation, enhancement, help wanted

#34 Sprint3 - v0.2.0 Release
  .circleci/config.yml
  .github/workflows/codeql-analysis-feature.yml
  .github/workflows/python-app-feature.yml
  .gitignore
  dev_setup.sh
  docs/wiki/usage/index.md
  requirements.txt
  run_tests.sh
  src/__pycache__/net_propagation.cpython-310-pytest-6.2.5.pyc
  src/__pycache__/net_propagation.cpython-310.pyc
  src/__pycache__/strings.cpython-310.pyc
  src/__pycache__/test_net_propagation.cpython-310-pytest-6.2.5.pyc
  src/main.py
  src/net_propagation.py
  src/strings.py
  src/test_files/file.txt
  src/test_files/ip_list.txt
  src/test_files/passwords_list.txt
  src/test_net_propagation.py
Labels: enhancement

#35 Sprint3 - v0.2.0 Release
  .circleci/config.yml
  .github/workflows/codeql-analysis-feature.yml
  .github/workflows/python-app-feature.yml
  .gitignore
  dev_setup.sh
  docs/wiki/usage/index.md
  requirements.txt
  run_tests.sh
  src/__pycache__/net_propagation.cpython-310-pytest-6.2.5.pyc
  src/__pycache__/net_propagation.cpython-310.pyc
  src/__pycache__/strings.cpython-310.pyc
  src/__pycache__/test_net_propagation.cpython-310-pytest-6.2.5.pyc
  src/main.py
  src/net_propagation.py
  src/strings.py
  src/test_files/file.txt
  src/test_files/ip_list.txt
  src/test_files/passwords_list.txt
  src/test_net_propagation.py
Labels: enhancement

#37 Adding CodeFactor Badge
  README.md
Labels: documentation
